package com.adisastrawan.jetpacksubmission.model

import com.adisastrawan.jetpacksubmission.R
object FakeData{
    val champions = championsName.mapIndexed { index, name ->
        Champion(
            name = name,
            description = championsDesc[index],
            img = championsDrawableIds[index],
            subname = championsSubnames[index],
            role = championsRoles[index],
            difficulty = championsDifficulties[index]
        )
    }
}
val championsName = listOf(
    "Aatrox",
    "Ahri",
    "Akali",
    "Bard",
    "Bel'Veth",
    "Blitzcrank",
    "Caitlyn",
    "Camille",
    "Cassiopeia",
    "Darius",
    "Diana",
    "Dr.Mundo",
    "Ekko",
    "Elise",
    "Evelynn",
    "Fiddlesticks",
    "Fiora",
    "Fizz",
    "Galio",
    "Gangplank",
    "Garen",
    "Hecarim",
    "Heimerdinger",
    "Hwei",
    "Illaoi",
    "Irelia",
    "Ivern",
    "Janna",
    "Jarvan IV",
    "Jax",
    "Jhin",
    "Kai'Sa",
    "Kalista",
    "K'sante",
    "Leblanc",
    "Lee Sin",
    "Leona",
    "Malphite",
    "Malzahar",
    "Maokai",
    "Naafiri",
    "Nami",
    "Nasus",
    "Olaf",
    "Orianna",
    "Ornn",
    "Pantheon",
    "Poppy",
    "Pyke",
    "Qiyana",
    "Quinn",
    "Rakan",
    "Rammus",
    "Rek'Sai",
    "Samira",
    "Sejuani",
    "Senna",
    "Tahm Kench",
    "Taliyah",
    "Talon",
    "Udyr",
    "Urgot",
    "Varus",
    "Vayne",
    "Veigar",
    "Warwick",
    "Wukong",
    "Xayah",
    "Xerath",
    "Xin Zhao",
    "Yasuo",
    "Yone",
    "Yorick",
    "Zac",
    "Zed",
    "Zeri"
)

val championsDrawableIds = listOf(
    R.drawable.aatrox,
    R.drawable.ahri,
    R.drawable.akali,
    R.drawable.bard,
    R.drawable.belveth,
    R.drawable.blitzcrank,
    R.drawable.caitlyn,
    R.drawable.camille,
    R.drawable.cassiopeia,
    R.drawable.darius,
    R.drawable.diana,
    R.drawable.drmundo,
    R.drawable.ekko,
    R.drawable.elise,
    R.drawable.evelynn,
    R.drawable.fiddlesticks,
    R.drawable.fiora,
    R.drawable.fizz,
    R.drawable.galio,
    R.drawable.gangplank,
    R.drawable.garen,
    R.drawable.hecarim,
    R.drawable.heimerdinger,
    R.drawable.hwei,
    R.drawable.illaoi,
    R.drawable.irelia,
    R.drawable.ivern,
    R.drawable.janna,
    R.drawable.jarvaniv,
    R.drawable.jax,
    R.drawable.jhin,
    R.drawable.kaisa,
    R.drawable.kalista,
    R.drawable.ksante,
    R.drawable.leblanc,
    R.drawable.leesin,
    R.drawable.leona,
    R.drawable.malphite,
    R.drawable.malzahar,
    R.drawable.maokai,
    R.drawable.naafiri,
    R.drawable.nami,
    R.drawable.nasus,
    R.drawable.olaf,
    R.drawable.orianna,
    R.drawable.ornn,
    R.drawable.pantheon,
    R.drawable.poppy,
    R.drawable.pyke,
    R.drawable.qiyana,
    R.drawable.quinn,
    R.drawable.rakan,
    R.drawable.rammus,
    R.drawable.reksai,
    R.drawable.samira,
    R.drawable.sejuani,
    R.drawable.senna,
    R.drawable.tahmkench,
    R.drawable.taliyah,
    R.drawable.talon,
    R.drawable.udyr,
    R.drawable.urgot,
    R.drawable.varus,
    R.drawable.vayne,
    R.drawable.veigar,
    R.drawable.warwick,
    R.drawable.wukong,
    R.drawable.xayah,
    R.drawable.xerath,
    R.drawable.xinzhao,
    R.drawable.yasuo,
    R.drawable.yone,
    R.drawable.yorick,
    R.drawable.zac,
    R.drawable.zed,
    R.drawable.zeri
)
val championsDesc = listOf(

    "Once honored defenders of Shurima against the Void, Aatrox and his brethren would eventually become an even greater threat to Runeterra, and were defeated only by cunning mortal sorcery. But after centuries of imprisonment, Aatrox was the first to find freedom once more, corrupting and transforming those foolish enough to try and wield the magical weapon that contained his essence. Now, with stolen flesh, he walks Runeterra in a brutal approximation of his previous form, seeking an apocalyptic and long overdue vengeance.",
    "Innately connected to the magic of the spirit realm, Ahri is a fox-like vastaya who can manipulate her prey\'s emotions and consume their essence—receiving flashes of their memory and insight from each soul she consumes. Once a powerful yet wayward predator, Ahri is now traveling the world in search of remnants of her ancestors while also trying to replace her stolen memories with ones of her own making.",
    "Abandoning the Kinkou Order and her title of the Fist of Shadow, Akali now strikes alone, ready to be the deadly weapon her people need. Though she holds onto all she learned from her master Shen, she has pledged to defend Ionia from its enemies, one kill at a time. Akali may strike in silence, but her message will be heard loud and clear: fear the assassin with no master.",
    "A traveler from beyond the stars, Bard is an agent of serendipity who fights to maintain a balance where life can endure the indifference of chaos. Many Runeterrans sing songs that ponder his extraordinary nature, yet they all agree that the cosmic vagabond is drawn to artifacts of great magical power. Surrounded by a jubilant choir of helpful spirit meeps, it is impossible to mistake his actions as malevolent, as Bard always serves the greater good... in his own odd way.",
    "A nightmarish empress created from the raw material of an entire devoured city, Bel\'Veth is the end of Runeterra itself... and the beginning of a monstrous reality of her own design. Driven by epochs of repurposed history, knowledge, and memories from the world above, she voraciously feeds an ever-expanding need for new experiences and emotions, consuming all that crosses her path. Yet her wants could never be sated by only one world as she turns her hungry eyes toward the Void\'s old masters...",
    "Blitzcrank is an enormous, near-indestructible automaton from Zaun, originally built to dispose of hazardous waste. However, he found this primary purpose too restricting, and modified his own form to better serve the fragile people of the Sump. Blitzcrank selflessly uses his strength and durability to protect others, extending a helpful metal fist or burst of energy to subdue any troublemakers.",
    "Renowned as its finest peacekeeper, Caitlyn is also Piltover\'s best shot at ridding the city of its elusive criminal elements. She is often paired with Vi, acting as a cool counterpoint to her partner\'s more impetuous nature. Even though she carries a one-of-a-kind hextech rifle, Caitlyn\'s most powerful weapon is her superior intellect, allowing her to lay elaborate traps for any lawbreakers foolish enough to operate in the City of Progress.",
    "Weaponized to operate outside the boundaries of the law, Camille is the Principal Intelligencer of Clan Ferros—an elegant and elite agent who ensures the Piltover machine and its Zaunite underbelly runs smoothly. Adaptable and precise, she views sloppy technique as an embarrassment that must be put to order. With a mind as sharp as the blades she bears, Camille\'s pursuit of superiority through hextech body augmentation has left many to wonder if she is now more machine than woman.",
    "Cassiopeia is a deadly creature bent on manipulating others to her sinister will. Youngest and most beautiful daughter of the noble Du Couteau family of Noxus, she ventured deep into the crypts beneath Shurima in search of ancient power. There, she was bitten by a gruesome tomb guardian, whose venom transformed her into a viper-like predator. Cunning and agile, Cassiopeia now slithers under the veil of night, petrifying her enemies with her baleful gaze.",
    "There is no greater symbol of Noxian might than Darius, the nation\'s most feared and battle-hardened commander. Rising from humble origins to become the Hand of Noxus, he cleaves through the empire\'s enemies—many of them Noxians themselves. Knowing that he never doubts his cause is just, and never hesitates once his axe is raised, those who stand against the leader of the Trifarian Legion can expect no mercy.",
    "Bearing her crescent moonblade, Diana fights as a warrior of the Lunari—a faith all but quashed in the lands around Mount Targon. Clad in shimmering armor the color of winter snow at night, she is a living embodiment of the silver moon\'s power. Imbued with the essence of an Aspect from beyond Targon\'s towering summit, Diana is no longer wholly human, and struggles to understand her power and purpose in this world.",
    "Utterly mad, tragically homicidal, and horrifyingly purple, Dr. Mundo is what keeps many of Zaun\'s citizens indoors on particularly dark nights. Now a self-proclaimed physician, he was once a patient of Zaun\'s most infamous asylum. After \"curing\" the entire staff, Dr. Mundo established his practice in the empty wards that once treated him and began mimicking the highly unethical procedures he had so often experienced himself. With a full cabinet of medicines and zero medical knowledge, he now makes himself more monstrous with each injection and terrifies the hapless \"patients\" who wander near his office.",
    "A prodigy from the rough streets of Zaun, Ekko manipulates time to twist any situation to his advantage. Using his own invention, the Zero Drive, he explores the branching possibilities of reality to craft the perfect moment. Though he revels in this freedom, when there\'s a threat to his friends he\'ll do anything to defend them. To outsiders, Ekko seems to achieve the impossible the first time, every time.",
    "Elise is a deadly predator who dwells in a shuttered, lightless palace, deep within the oldest city of Noxus. Once mortal, she was the mistress of a powerful house, but the bite of a vile demigod transformed her into something beautiful, yet utterly inhuman—a spider-like creature, drawing unsuspecting prey into her web. To maintain her eternal youth, Elise now prefers to feed upon the naive and the faithless, and there are few who can resist her seductions.",
    "Within the dark seams of Runeterra, the demon Evelynn searches for her next victim. She lures in prey with the voluptuous façade of a human female, but once a person succumbs to her charms, Evelynn\'s true form is unleashed. She then subjects her victim to unspeakable torment, gratifying herself with their pain. To the demon, these liaisons are innocent flings. To the rest of Runeterra, they are ghoulish tales of lust gone awry and horrific reminders of the cost of wanton desire.",
    " Something has awoken in Runeterra. Something ancient. Something terrible. The ageless horror known as Fiddlesticks stalks the edges of mortal society, drawn to areas thick with paranoia where it feeds upon terrorized victims. Wielding a jagged scythe, the haggard, makeshift creature reaps fear itself, shattering the minds of those unlucky enough to survive in its wake. Beware the sounding of the crow, or the whispering of the shape that appears almost human Fiddlesticks has returned ",
    "The most feared duelist in all Valoran, Fiora is as renowned for her brusque manner and cunning mind as she is for the speed of her bluesteel rapier. Born to House Laurent in the kingdom of Demacia, Fiora took control of the family from her father in the wake of a scandal that nearly destroyed them. House Laurent\'s reputation was sundered, but Fiora bends her every effort to restore her family\'s honor and return them to their rightful place among the great and good of Demacia.",
    "Fizz is an amphibious yordle, who dwells among the reefs surrounding Bilgewater. He often retrieves and returns the tithes cast into the sea by superstitious captains, but even the saltiest of sailors know better than to cross him—for many are the tales of those who have underestimated this slippery character. Often mistaken for some manner of capricious ocean spirit, he seems able to command the beasts of the deep, and delights in confounding his allies and enemies alike.",
    "Outside the gleaming city of Demacia, the stone colossus Galio keeps vigilant watch. Built as a bulwark against enemy mages, he often stands motionless for decades until the presence of powerful magic stirs him to life. Once activated, Galio makes the most of his time, savoring the thrill of a fight and the rare honor of defending his countrymen. But his triumphs are always bittersweet, for the magic he destroys is also his source of reanimation, and each victory leaves him dormant once again.",
    "As unpredictable as he is brutal, the dethroned reaver king Gangplank is feared far and wide. Once, he ruled the port city of Bilgewater, and while his reign is over, there are those who believe this has only made him more dangerous. Gangplank would see Bilgewater bathed in blood once more before letting someone else take it—and now with pistol, cutlass, and barrels of gunpowder, he is determined to reclaim what he has lost.",
    "A proud and noble warrior, Garen fights as one of the Dauntless Vanguard. He is popular among his fellows, and respected well enough by his enemies—not least as a scion of the prestigious Crownguard family, entrusted with defending Demacia and its ideals. Clad in magic-resistant armor and bearing a mighty broadsword, Garen stands ready to confront mages and sorcerers on the field of battle, in a veritable whirlwind of righteous steel.",
    "Hecarim is a spectral fusion of man and beast, cursed to ride down the souls of the living for all eternity. When the Blessed Isles fell into shadow, this proud knight was obliterated by the destructive energies of the Ruination, along with all his cavalry and their mounts. Now, whenever the Black Mist reaches out across Runeterra, he leads their devastating charge, reveling in the slaughter and crushing the foe beneath his armored hooves.",
    "A brilliant yet eccentric yordle scientist, Professor Cecil B. Heimerdinger is one of the most innovative and esteemed inventors Piltover has ever known. Relentless in his work to the point of neurotic obsession, he thrives on answering the universe\'s most impenetrable questions. Though his theories often appear opaque and esoteric, Heimerdinger has crafted some of Piltover\'s most miraculous—not to mention lethal—machinery, and constantly tinkers with his inventions to make them even more efficient.",
    "Hwei is a brooding painter who creates brilliant art in order to confront Ionia\'s criminals and comfort their victims. Beneath his melancholy roils a torn, emotional mind—haunted by both the vibrant visions of his imagination and the gruesome memories of his temple\'s massacre. Hwei seeks to understand this light and dark, which drives him inevitably toward the artist who unraveled him. With paintbrush and palette, Hwei shapes endless possibilities as he draws ever closer to earning closure or embracing despair.",
    "Illaoi\'s powerful physique is dwarfed only by her indomitable faith. As the prophet of the Great Kraken, she uses a huge, golden idol to rip her foes\' spirits from their bodies and shatter their perception of reality. All who challenge the “Truth Bearer of Nagakabouros” soon discover Illaoi never battles alone—the god of the Serpent Isles fights by her side.",
    "The Noxian occupation of Ionia produced many heroes, none more unlikely than young Irelia of Navori. Trained in the ancient dances of her province, she adapted her art for war, using the graceful and carefully practised movements to levitate a host of deadly blades. After proving herself as a fighter, she was thrust into the role of resistance leader and figurehead, and to this day remains dedicated to the preservation of her homeland.",
    "Ivern Bramblefoot, known to many as the Green Father, is a peculiar half man, half tree who roams Runeterra\'s forests, cultivating life everywhere he goes. He knows the secrets of the natural world, and holds deep friendships with all things that grow, fly, and scuttle. Ivern wanders the wilderness, imparting strange wisdom to any he meets, enriching the forests, and occasionally entrusting loose-lipped butterflies with his secrets.",
    "Armed with the power of Runeterra\'s gales, Janna is a mysterious, elemental wind spirit who protects the dispossessed of Zaun. Some believe she was brought into existence by the pleas of Runeterra\'s sailors who prayed for fair winds as they navigated treacherous waters and braved rough tempests. Her favor and protection has since been called into the depths of Zaun, where Janna has become a beacon of hope to those in need. No one knows where or when she will appear, but more often than not, she\'s come to help.",
    "Prince Jarvan, scion of the Lightshield dynasty, is heir apparent to the throne of Demacia. Raised to be a paragon of his nation\'s greatest virtues, he is forced to balance the heavy expectations placed upon him with his own desire to fight on the front lines. Jarvan inspires his troops with his fearsome courage and selfless determination, raising his family\'s colors high and revealing his true strength as a future leader of his people.",
    "Unmatched in both his skill with unique armaments and his biting sarcasm, Jax is the last known weapons master of Icathia. After his homeland was laid low by its own hubris in unleashing the Void, Jax and his kind vowed to protect what little remained. As magic now rises in the world, this slumbering threat stirs once more, and Jax roams Valoran, wielding the last light of Icathia and testing all warriors he meets to see if any are strong enough to stand beside him...",
    "Jhin is a meticulous criminal psychopath who believes murder is art. Once an Ionian prisoner, but freed by shadowy elements within Ionia\'s ruling council, the serial killer now works as their cabal\'s assassin. Using his gun as his paintbrush, Jhin creates works of artistic brutality, horrifying victims and onlookers. He gains a cruel pleasure from putting on his gruesome theater, making him the ideal choice to send the most powerful of messages: terror.",
    "Claimed by the Void when she was only a child, Kai\'Sa managed to survive through sheer tenacity and strength of will. Her experiences have made her a deadly hunter and, to some, the harbinger of a future they would rather not live to see. Having entered into an uneasy symbiosis with a living Void carapace, the time will soon come when she must decide whether to forgive those mortals who would call her a monster, and defeat the coming darkness together… or simply to forget, as the Void consumes the world that left her behind.",
    "A specter of wrath and retribution, Kalista is the undying spirit of vengeance, an armored nightmare summoned from the Shadow Isles to hunt deceivers and traitors. The betrayed may cry out in blood to be avenged, but Kalista only answers those willing to pay with their very souls. Those who become the focus of Kalista\'s wrath should make their final peace, for any pact sealed with this grim hunter can only end with the cold, piercing fire of her soul-spears.",
    "Defiant and courageous, K\'Sante battles colossal beasts and ruthless Ascended to protect his home of Nazumah, a coveted oasis amid the sands of Shurima. But after a falling-out with his former partner, K\'Sante realizes that in order to become a warrior worthy of leading his city, he must temper his single-minded drive for success. Only then can he avoid falling prey to his own pride and find the wisdom he needs to defeat the vicious monsters threatening his people.",
    "Mysterious even to other members of the Black Rose cabal, LeBlanc is but one of many names for a pale woman who has manipulated people and events since the earliest days of Noxus. Using her magic to mirror herself, the sorceress can appear to anyone, anywhere, and even be in many places at once. Always plotting just out of sight, LeBlanc\'s true motives are as inscrutable as her shifting identity.",
    "A master of Ionia\'s ancient martial arts, Lee Sin is a principled fighter who channels the essence of the dragon spirit to face any challenge. Though he lost his sight many years ago, the warrior-monk has devoted his life to protecting his homeland against any who would dare upset its sacred balance. Enemies who underestimate his meditative demeanor will endure his fabled burning fists and blazing roundhouse kicks.",
    "Imbued with the fire of the sun, Leona is a holy warrior of the Solari who defends Mount Targon with her Zenith Blade and the Shield of Daybreak. Her skin shimmers with starfire while her eyes burn with the power of the celestial Aspect within her. Armored in gold and bearing a terrible burden of ancient knowledge, Leona brings enlightenment to some, death to others.",
    "A massive creature of living stone, Malphite struggles to impose blessed order on a chaotic world. Birthed as a servitor-shard to an otherworldly obelisk known as the Monolith, he used his tremendous elemental strength to maintain and protect his progenitor, but ultimately failed. The only survivor of the destruction that followed, Malphite now endures Runeterra\'s soft folk and their fluid temperaments, while struggling to find a new role worthy of the last of his kind.",
    "A zealous seer dedicated to the unification of all life, Malzahar truly believes the newly emergent Void to be the path to Runeterra\'s salvation. In the desert wastes of Shurima, he followed the voices that whispered in his mind, all the way to ancient Icathia. Amidst the ruins of that land, he gazed into the dark heart of the Void itself, and was gifted new power and purpose. Malzahar now sees himself as a shepherd, empowered to bring others into the fold… or to release the voidling creatures that dwell beneath.",
    "Maokai is a rageful, towering treant who fights the unnatural horrors of the Shadow Isles. He was twisted into a force of vengeance after a magical cataclysm destroyed his home, surviving undeath only through the Waters of Life infused within his heartwood. Once a peaceful nature spirit, Maokai now furiously battles to banish the scourge of unlife from the Shadow Isles and restore his home to its former beauty.",
    "Across the sands of Shurima, a chorus of howls rings out. It is the call of the dune hounds, voracious predators who form packs and compete for the right to hunt in these barren lands. Among them, one pack stands above all, for they are driven not only by canine instincts, but by the ancient power of the Darkin.",
    "A headstrong young vastaya of the seas, Nami was the first of the Marai tribe to leave the waves and venture onto dry land, when their ancient accord with the Targonians was broken. With no other option, she took it upon herself to complete the sacred ritual that would ensure the safety of her people. Amidst the chaos of this new age, Nami faces an uncertain future with grit and determination, using her Tidecaller staff to summon the strength of the oceans themselves.",
    "Nasus is an imposing, jackal-headed Ascended being from ancient Shurima, a heroic figure regarded as a demigod by the people of the desert. Fiercely intelligent, he was a guardian of knowledge and peerless strategist whose wisdom guided the ancient empire of Shurima to greatness for many centuries. After the fall of the empire, he went into self-imposed exile, becoming little more than a legend. Now that the ancient city of Shurima has risen once more, he has returned, determined to ensure it never falls again.",
    "An unstoppable force of destruction, the axe-wielding Olaf wants nothing but to die in glorious combat. Hailing from the brutal Freljordian peninsula of Lokfar, he once received a prophecy foretelling his peaceful passing—a coward\'s fate, and a great insult among his people. Seeking death, and fueled by rage, he rampaged across the land, slaughtering scores of great warriors and legendary beasts in search of any opponent who could stop him. Now a brutal enforcer for the Winter\'s Claw, he seeks his end in the great wars to come.",
    "Once a curious girl of flesh and blood, Orianna is now a technological marvel comprised entirely of clockwork. She became gravely ill after an accident in the lower districts of Zaun, and her failing body had to be replaced with exquisite artifice, piece by piece. Accompanied by an extraordinary brass sphere she built for companionship and protection, Orianna is now free to explore the wonders of Piltover, and beyond.",
    "Ornn is the Freljordian spirit of forging and craftsmanship. He works in the solitude of a massive smithy, hammered out from the lava caverns beneath the volcano Hearth-Home. There he stokes bubbling cauldrons of molten rock to purify ores and fashion items of unsurpassed quality. When other deities—especially Volibear—walk the earth and meddle in mortal affairs, Ornn arises to put these impetuous beings back in their place, either with his trusty hammer or the fiery power of the mountains themselves.",
    "Once an unwilling host to the Aspect of War, Atreus survived when the celestial power within him was slain, refusing to succumb to a blow that tore stars from the heavens. In time, he learned to embrace the power of his own mortality, and the stubborn resilience that goes along with it. Atreus now opposes the divine as Pantheon reborn, his unbreakable will fueling the fallen Aspect\'s weapons on the field of battle.",
    "Runeterra has no shortage of valiant champions, but few are as tenacious as Poppy. Bearing the legendary hammer of Orlon, a weapon twice her size, this determined yordle has spent untold years searching in secret for the fabled “Hero of Demacia,” said to be its rightful wielder. Until then, she dutifully charges into battle, pushing back the kingdom\'s enemies with every whirling strike.",
    "A renowned harpooner from the slaughter docks of Bilgewater, Pyke should have met his death in the belly of a gigantic jaull-fish… and yet, he returned. Now, stalking the dank alleys and backways of his former hometown, he uses his new supernatural gifts to bring a swift and gruesome end to those who make their fortune by exploiting others—and a city that prides itself on hunting monsters now finds a monster hunting them.",
    "In the jungle city of Ixaocan, Qiyana plots her own ruthless path to the high seat of the Yun Tal. Last in line to succeed her parents, she faces those who stand in her way with brash confidence and unprecedented mastery over elemental magic. With the land itself obeying her every command, Qiyana sees herself as the greatest elementalist in the history of Ixaocan—and by that right, deserving of not only a city, but an empire.",
    "Quinn is an elite ranger-knight of Demacia, who undertakes dangerous missions deep in enemy territory. She and her legendary eagle, Valor, share an unbreakable bond, and their foes are often slain before they realize they are fighting not one, but two of the kingdom\'s greatest heroes. Nimble and acrobatic when required, Quinn takes aim with her crossbow while Valor marks their elusive targets from above, making them a deadly pair on the battlefield.",
    "As mercurial as he is charming, Rakan is an infamous vastayan troublemaker and the greatest battle-dancer in Lhotlan tribal history. To the humans of the Ionian highlands, his name has long been synonymous with wild festivals, uncontrollable parties, and anarchic music. Few would suspect this energetic, traveling showman is also partner to the rebel Xayah, and is dedicated to her cause.",
    "Idolized by many, dismissed by some, mystifying to all, the curious being Rammus is an enigma. Protected by a spiked shell, he inspires increasingly disparate theories on his origin wherever he goes—from demigod, to sacred oracle, to a mere beast transformed by magic. Whatever the truth may be, Rammus keeps his own counsel and stops for no one as he roams the Shuriman desert.",
    "An apex predator, Rek\'Sai is a merciless Void-spawn that tunnels beneath the ground to ambush and devour unsuspecting prey. Her insatiable hunger has laid waste to entire regions of the once-great empire of Shurima—merchants, traders, even armed caravans, will go hundreds of miles out of their way to avoid her and her offspring\'s hunting grounds. All know that once Rek\'Sai is seen on the horizon, death from below is all but guaranteed.",
    "Samira stares death in the eye with unyielding confidence, seeking thrill wherever she goes. After her Shuriman home was destroyed as a child, Samira found her true calling in Noxus, where she built a reputation as a stylish daredevil taking on dangerous missions of the highest caliber. Wielding black-powder pistols and a custom-engineered blade, Samira thrives in life-or-death circumstances, eliminating any who stand in her way with flash and flair.",
    "Sejuani is the brutal, unforgiving Iceborn warmother of the Winter\'s Claw, one of the most feared tribes of the Freljord. Her people\'s survival is a constant, desperate battle against the elements, forcing them to raid Noxians, Demacians, and Avarosans alike to survive the harsh winters. Sejuani herself spearheads the most dangerous of these attacks from the saddle of her drüvask boar Bristle, using her True Ice flail to freeze and shatter her enemies.",
    "Cursed from childhood to be haunted by the supernatural Black Mist, Senna joined a sacred order known as the Sentinels of Light, and fiercely fought back—only to be killed, her soul imprisoned in a lantern by the cruel wraith Thresh. But refusing to lose hope, within the lantern Senna learned to use the Mist, and reemerged to new life, forever changed. Now wielding darkness along with light, Senna seeks to end the Black Mist by turning it against itself—with every blast of her relic weapon, redeeming the souls lost within.",
    "Known by many names throughout history, the demon Tahm Kench travels the waterways of Runeterra, feeding his insatiable appetite with the misery of others. Though he may appear singularly charming and proud, he swaggers through the physical realm like a vagabond in search of unsuspecting prey. His lashing tongue can stun even a heavily armored warrior from a dozen paces, and to fall into his rumbling belly is to tumble into an abyss from which there is little hope of return.",
    "Taliyah is a nomadic mage from Shurima, torn between teenage wonder and adult responsibility. She has crossed nearly all of Valoran on a journey to learn the true nature of her growing powers, though more recently she has returned to protect her tribe. Some have mistaken her compassion for weakness and paid the ultimate price—for beneath Taliyah\'s youthful demeanor is a will strong enough to move mountains, and a spirit fierce enough to make the earth itself tremble.",
    "Talon is the knife in the darkness, a merciless killer able to strike without warning and escape before any alarm is raised. He carved out a dangerous reputation on the brutal streets of Noxus, where he was forced to fight, kill, and steal to survive. Adopted by the notorious Du Couteau family, he now plies his deadly trade at the empire\'s command, assassinating enemy leaders, captains, and heroes… as well as any Noxian foolish enough to earn the scorn of their masters.",
    "The most powerful spirit walker alive, Udyr communes with all the spirits of the Freljord, whether by empathically understanding their needs, or by channeling and transforming their ethereal energy into his own primal fighting style. He seeks balance within, so that his mind does not get lost amidst others, but he also seeks balance without—for the Freljord\'s mystical landscape can only thrive with the growth that comes from conflict and struggle, and Udyr knows that sacrifices must be made to keep peaceful stagnance at bay.",
    "Once a powerful Noxian headsman, Urgot was betrayed by the empire for which he had killed so many. Bound in iron chains, he was forced to learn the true meaning of strength in the Dredge—a prison mine deep beneath Zaun. Emerging in a disaster that spread chaos throughout the city, he now casts an imposing shadow over its criminal underworld. Raising his victims on the very chains that once enslaved him, he will purge his new home of the unworthy, making it a crucible of pain.",
    "One of the ancient darkin, Varus was a deadly killer who loved to torment his foes, driving them almost to insanity before delivering the killing arrow. He was imprisoned at the end of the Great Darkin War, but escaped centuries later in the remade flesh of two Ionian hunters—they had unwittingly released him, cursed to bear the bow containing his bound essence. Varus now seeks out those who trapped him, in order to enact his brutal vengeance, but the mortal souls within still resist him every step of the way.",
    "Shauna Vayne is a deadly, remorseless Demacian monster hunter, who has dedicated her life to finding and destroying the demon that murdered her family. Armed with a wrist-mounted crossbow and a heart full of vengeance, she is only truly happy when slaying practitioners or creations of the dark arts, striking from the shadows with a flurry of silver bolts.",
    "An enthusiastic master of dark sorcery, Veigar has embraced powers that few mortals dare approach. As a free-spirited inhabitant of Bandle City, he longed to push beyond the limitations of yordle magic, and turned instead to arcane texts that had been hidden away for thousands of years. Now a stubborn creature with an endless fascination for the mysteries of the universe, Veigar is often underestimated by others—but even though he believes himself truly evil, he possesses an inner morality that leads some to question his deeper motivations.",
    "Warwick is a monster who hunts the gray alleys of Zaun. Transformed by agonizing experiments, his body is fused with an intricate system of chambers and pumps, machinery filling his veins with alchemical rage. Bursting out of the shadows, he preys upon those criminals who terrorize the city\'s depths. Warwick is drawn to blood, and driven mad by its scent. None who spill it can escape him.",
    "Wukong is a vastayan trickster who uses his strength, agility, and intelligence to confuse his opponents and gain the upper hand. After finding a lifelong friend in the warrior known as Master Yi, Wukong became the last student of the ancient martial art known as Wuju. Armed with an enchanted staff, Wukong seeks to prevent Ionia from falling to ruin.",
    "Deadly and precise, Xayah is a vastayan revolutionary waging a personal war to save her people. She uses her speed, guile, and razor-sharp feather blades to cut down anyone who stands in her way. Xayah fights alongside her partner and lover, Rakan, to protect their dwindling tribe, and restore their race to her vision of its former glory.",
    "Xerath is an Ascended Magus of ancient Shurima, a being of arcane energy writhing in the broken shards of a magical sarcophagus. For millennia, he was trapped beneath the desert sands, but the rise of Shurima freed him from his ancient prison. Driven insane with power, he now seeks to take what he believes is rightfully his and replace the upstart civilizations of the world with one fashioned in his image.",
    "Xin Zhao is a resolute warrior loyal to the ruling Lightshield dynasty. Once condemned to the fighting pits of Noxus, he survived countless gladiatorial bouts, but after being freed by Demacian forces, he swore his life and allegiance to these brave liberators. Armed with his favored three-talon spear, Xin Zhao now fights for his adopted kingdom, audaciously challenging any foe, no matter the odds.",
    "An Ionian of deep resolve, Yasuo is an agile swordsman who wields the air itself against his enemies. As a proud young man, he was falsely accused of murdering his master—unable to prove his innocence, he was forced to slay his own brother in self defense. Even after his master\'s true killer was revealed, Yasuo still could not forgive himself for all he had done, and now wanders his homeland with only the wind to guide his blade.",
    "In life, he was Yone—half-brother of Yasuo, and renowned student of his village\'s sword school. But upon his death at the hands of his brother, he found himself hunted by a malevolent entity of the spirit realm, and was forced to slay it with its own sword. Now, cursed to wear its demonic mask upon his face, Yone tirelessly hunts all such creatures in order to understand what he has become.",
    "The last survivor of a long-forgotten religious order, Yorick is both blessed and cursed with power over the dead. Trapped on the Shadow Isles, his only companions are the rotting corpses and shrieking spirits that he gathers to him. Yorick\'s monstrous actions belie his noble purpose: to free his home from the curse of the Ruination.",
    "Zac is the product of a toxic spill that ran through a chemtech seam and pooled in an isolated cavern deep in Zaun\'s Sump. Despite such humble origins, Zac has grown from primordial ooze into a thinking being who dwells in the city\'s pipes, occasionally emerging to help those who cannot help themselves or to rebuild the broken infrastructure of Zaun.",
    "Utterly ruthless and without mercy, Zed is the leader of the Order of Shadow, an organization he created with the intent of militarizing Ionia\'s magical and martial traditions to drive out Noxian invaders. During the war, desperation led him to unlock the secret shadow form—a malevolent spirit magic as dangerous and corrupting as it is powerful. Zed has mastered all of these forbidden techniques to destroy anything he sees as a threat to his nation, or his new order.",
    "A headstrong, spirited young woman from Zaun\'s working-class, Zeri channels her electric magic to charge herself and her custom-crafted gun. Her volatile power mirrors her emotions, its sparks reflecting her lightning-fast approach to life. Deeply compassionate toward others, Zeri carries the love of her family and her home into every fight. Though her eagerness to help can sometimes backfire, Zeri believes one truth to be certain: stand up for your community, and it will stand up with you.",
)
val championsRoles = listOf(
    "Fighter", "Mage", "Assassin", "Support", "Assassin", "Support", "Marksman", "Fighter", "Mage",
    "Fighter", "Fighter", "Fighter", "Assassin", "Mage", "Assassin", "Mage", "Fighter", "Assassin",
    "Tank", "Fighter", "Tank", "Fighter", "Mage", "Mage", "Fighter", "Fighter", "Support",
    "Support", "Fighter", "Fighter", "Marksman", "Marksman", "Marksman", "Fighter", "Mage", "Assassin",
    "Tank", "Tank", "Mage", "Support", "Mage", "Support", "Fighter", "Fighter", "Mage", "Fighter",
    "Fighter", "Tank", "Support", "Assassin", "Marksman", "Support", "Tank", "Assassin", "Marksman",
    "Fighter", "Marksman", "Support", "Mage", "Assassin", "Fighter", "Fighter", "Marksman", "Marksman",
    "Mage", "Fighter", "Fighter", "Marksman", "Mage", "Fighter", "Assassin", "Fighter", "Fighter",
    "Fighter", "Assassin", "Marksman"
)

val championsDifficulties = listOf(
    "Moderate", "Moderate", "Moderate", "Moderate", "Moderate", "High", "Low", "Moderate", "Moderate",
    "Low", "Moderate", "Low", "Moderate", "Moderate", "Moderate", "High", "Low", "High", "Moderate",
    "Moderate", "Low", "Moderate", "Moderate", "High", "Moderate", "High", "Moderate", "Moderate",
    "Moderate", "Low", "Moderate", "Moderate", "High", "High", "High", "High", "Low", "Moderate",
    "Low", "Moderate", "Low", "Low", "Low", "Low", "Low", "Moderate", "Moderate", "Moderate",
    "Moderate", "Moderate", "Moderate", "Moderate", "Moderate", "Moderate", "Low", "High", "Moderate",
    "Moderate", "Moderate", "Moderate", "Moderate", "Moderate", "Moderate", "Low", "Moderate", "Low",
    "Low", "Low", "Low", "Low", "Moderate", "Moderate", "Moderate", "Moderate", "High", "Moderate",
    "High", "Moderate", "Moderate", "Moderate"
)

val championsSubnames = listOf(
    "THE DARKIN BLADE", "THE NINE-TAILED FOX", "THE ROGUE ASSASSIN", "THE WANDERING CARETAKER",
    "THE EMPRESS OF THE VOID", "THE GREAT STEAM GOLEM", "THE SHERIFF OF PILTOVER", "THE STEEL SHADOW",
    "THE SERPENT'S EMBRACE", "THE HAND OF NOXUS", "SCORN OF THE MOON", "THE MADMAN OF ZAUN",
    "THE BOY WHO SHATTERED TIME", "THE SPIDER QUEEN", "AGONY'S EMBRACE", "THE ANCIENT FEAR",
    "THE GRAND DUELIST", "THE TIDAL TRICKSTER", "THE COLOSSUS", "THE SALTWATER SCOURGE",
    "THE MIGHT OF DEMACIA", "THE SHADOW OF WAR", "THE REVERED INVENTOR", "THE VISIONARY",
    "THE KRAKEN PRIESTESS", "THE BLADE DANCER", "THE GREEN FATHER", "THE STORM'S FURY",
    "THE EXEMPLAR OF DEMACIA", "GRANDMASTER AT ARMS", "THE VIRTUOSO", "DAUGHTER OF THE VOID",
    "THE SPEAR OF VENGEANCE", "THE PRIDE OF NAZUMAH", "THE DECEIVER", "THE BLIND MONK",
    "THE RADIANT DAWN", "SHARD OF THE MONOLITH", "THE PROPHET OF THE VOID", "HE TWISTED TREANT",
    "THE HOUND OF A HUNDRED BITES", "THE TIDECALLER", "THE CURATOR OF THE SANDS", "THE BERSERKER",
    "THE LADY OF CLOCKWORK", "THE FIRE BELOW THE MOUNTAIN", "THE UNBREAKABLE SPEAR", "KEEPER OF THE HAMMER",
    "THE BLOODHARBOR RIPPER", "EMPRESS OF THE ELEMENTS", "DEMACIA'S WINGS", "THE CHARMER",
    "THE ARMORDILLO", "THE VOID BURROWER", "THE DESERT ROSE", "FURY OF THE NORTH", "THE REDEEMER",
    "THE RIVER KING", "THE STONEWEAVER", "THE BLADE'S SHADOW", "THE SPIRIT WALKER", "THE DREADNOUGHT",
    "THE ARROW OF RETRIBUTION", "THE NIGHT HUNTER", "THE TINY MASTER OF EVIL", "THE UNCAGED WRATH OF ZAUN",
    "THE MONKEY KING", "THE REBEL", "THE MAGUS ASCENDANT", "THE SENESCHAL OF DEMACIA", "THE UNFORGIVEN",
    "THE UNFORGOTTEN", "SHEPHERD OF SOULS", "THE SECRET WEAPON", "THE MASTER OF SHADOWS",
    "THE SPARK OF ZAUN"
)

